### ISSUE TITLE
trans_level, depth ?

### ISSUE THREAD

**Issue by leoneleone** [syssi/xiaomi_airhumidifier#2]
@syssi 
What does ‘trans_level’ property? Does it mean the remaining water reading?
Or is ‘depth’ indicating the water level? 

Thanks

**Comment by syssi** [comment]
```
humidifier_water_level_low_alert: Not enough water
humidifier_dry: 风干模式 / Dry mode
humidifier_sub_dry: 水量不足时继续运行约8小时 / Running about 8 hours when there is not enough water
humidifier_water_depth_text: 剩余水量 / The amount of water left
humidifier_water_depth: 剩余水量 %s%% / The remaining amount of water %s percent
```

Could you provide some example values?

**Comment by syssi** [comment]
Oddly enough `trans_level` is also called "strong mode".

**Comment by syssi** [comment]
Could you explain the "dry mode" if you have a clue? It's a button at the UI. Honestly I don't understand the provided label. ;-)

**Comment by leoneleone** [comment]
From the iOS MiHome app:

![af5345b7-654b-4a5f-b782-6e737fbf8b34](https://user-images.githubusercontent.com/13733361/38294257-2c7d60f6-37e2-11e8-8be2-70022f503393.jpeg)

**Comment by leoneleone** [comment]
@syssi 
What does strong mode exactly? 
I still don’t understand what Dry Mode does... what is ‘Dry Mode’? 

So Depth refers to Water Level, which is what I assumed. 👍🏼

**Comment by syssi** [comment]
I added some details here: https://github.com/rytilahti/python-miio/pull/300/files

**Comment by syssi** [comment]
The strong mode is just an operation mode / power mode. The interpretation of the trans_level is still unknown. It's only used to determine the strong mode is active and unused at recent firmware versions. A more accurate description of the dry mode could be this one:

Dry mode: The amount of water is not enough to continue to work for about 8 hours.

But it's still a mystery. ;-)

**Comment by leoneleone** [comment]
Thanks the additional info 🙏🏼
